# Generated by Django 4.0.6 on 2022-07-31 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('photo', models.ImageField(blank=True, help_text='Image submitted by user', null=True, upload_to='')),
                ('submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
